#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Chromium desktop='^1'
bspc rule -a TelegramDesktop desktop='^3'
bspc rule -a discord desktop='^3'
bspc rule -a obs desktop='^9'
bspc rule -a Godot state=floating

#setxkbmap -option grp:alt_shift_toggle us,ru &

$HOME/.config/polybar/launch.sh
wmname LG3D
wal -R

. "${HOME}/.config/dunst/launch.sh"

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color4"
bspc config presel_feedback_color "$color1"
